### ISSUE TITLE
Does this work for 3D?

### ISSUE THREAD

**Issue by SteveSmith16384** [organicpencil/godot-splitscreen#1]
I ask because the "total" viewport is not using the whole window.  I have a screen res of 1366x769, and I've set my Godot window size to 1920x1080 (so it should scale down).  In splitscreen.gd, it updates each player's view sizes based on the screen size (i.e. OS.window_size) which means that with 4 players, all 4 viewports only take up about 3 quarters of the screen.  The only way I can get it to fit nicely is if I set the Godot window size to be the same as whatever screen resolution I'm developing on at that time.  Am I doing something wrong?  Thanks.

**Comment by organicpencil** [comment]
Oh wow, super delayed response incoming. I gotta do something about all the github spam that I've been ignoring...

I tested on Windows 10 with Godot 3.1 and some newer ones. Setting the Godot window greater than the screen size does not scale it down, but rather extends the window beyond the screen's border, causing some of it to be cut off. When I try with fullscreen enabled, the resolution is clamped at the screen size. That's expected behavior and happens both with and without the addon.

I'd recommend setting the resolution to the smallest size you intend to develop on, which is basically what the Godot devs did when making 1024x600 the default.

Optional: Write code that saves/loads custom resolution in `user://`
